{% set version = "2.3.10" %}

package:
  name: qca
  version: {{ version }}

source:
  url: https://github.com/KDE/qca/archive/v{{ version }}.tar.gz
  sha256: c8af253cf515263246ea2be91a95978650a6c05d2698f2ba7286d297b352a0d4

build:
  number: 1
  skip: true  # [(win and vc<14) or ppc64le]

requirements:
  build:
    - cmake
    - make  # [unix]
    - ninja
    - pkg-config
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - qt6-main    # [build_platform != target_platform]
  host:
    - qt6-main
    - openssl
  run:
    - qt6-main
    - openssl

# Pass to cmake via the recipe's build script or via extra cmake args:
# -DBUILD_WITH_QT6=ON
# -DQCA_SUFFIX=qt6

test:
  commands:
    - test -f ${PREFIX}/lib/libqca-qt6.so  # [linux]
    - test -d ${PREFIX}/lib/qca-qt6.framework  # [osx]
    - if not exist %LIBRARY_BIN%\\qca-qt6.dll exit 1  # [win]
    - qcatool-qt6 --noprompt --newpass= key make rsa 2048 test.key  # [unix]
    - qcatool-qt6.exe --noprompt --newpass= key make rsa 2048 test.key  # [win]

about:
  home: https://userbase.kde.org/QCA
  license: LGPL-2.1-only
  license_file: COPYING
  summary: Qt Cryptographic Architecture (QCA) provides a straightforward and cross-platform crypto API, using Qt datatypes and conventions.
  description: |
    Taking a hint from the similarly-named Java Cryptography Architecture, QCA
    aims to provide a straightforward and cross-platform crypto API, using Qt
    datatypes and conventions. QCA separates the API from the implementation,
    using plugins known as Providers. The advantage of this model is to allow
    applications to avoid linking to or explicitly depending on any particular
    cryptographic library. This allows one to easily change or upgrade crypto
    implementations without even needing to recompile the application! QCA
    should work everywhere Qt does, including Windows/Unix/MacOSX.
  doc_url: https://api.kde.org/qca/html/
  dev_url: https://invent.kde.org/libraries/qca

extra:
  recipe-maintainers:
    - ceholden
    - izahn
    - gillins
    - SrNetoChan
